### ISSUE TITLE
Bad text quality in Windows

### ISSUE THREAD

**Issue by runiter** [dukke/Transit#5]
Unfortunately I had to downgrade to JMetro because the texts do not look good in Transit.
It appears that Transit works fine in Ubuntu but in Windows (dark mode) I get bad text rendering as shown below:

![image](https://github.com/user-attachments/assets/12a3da0a-1687-4041-9ed1-350d63e7e5e1)

Left windows is Transit. Right window in JMetro.

Notice how "File" and "Examples" menus are barely readable in Transit.

**Comment by dukke** [comment]
A new version of Transit with a completely revamped look and feel is just around the corner. Stay tuned. 
I'm going to close this issue as the new version has changed all controls.
If this happens in the new version, please file a bug report again.

Thanks Saeid!
